name: Deploy Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Позволяет запускать workflow вручную

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug secrets
        run: |
          if [ -z "${{ secrets.SERVER_HOST }}" ]; then
            echo "Error: SERVER_HOST is not set"
            exit 1
          fi
          echo "SERVER_HOST is configured"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: mishadeploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 30s
          command_timeout: 30m
          debug: true
          script: |
            echo "Setup deployment directory..."
            cd /opt/mishakrug_tg_bot
            sleep 5
            echo "Stopping existing process..."
            if pgrep -f "python3 mishakrug.py"; then
              pkill -f "python3 mishakrug.py"
              sleep 5
            fi
            sleep 5
            echo "Updating repository..."
            git pull origin main
            sleep 5
            echo "Starting new process..."
            source venv/bin/activate
            nohup python3 mishakrug.py > mishakrug.log 2>&1 &
            sleep 5
            echo "Deployment complete."
