name: Deploy Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Позволяет запускать workflow вручную

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug secrets
        run: |
          if [ -z "${{ secrets.SERVER_HOST }}" ]; then
            echo "Error: SERVER_HOST is not set"
            exit 1
          fi
          echo "SERVER_HOST is configured"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: mishadeploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 30s
          command_timeout: 30m
          debug: true
          script: |
            echo "Setup deployment directory..."
            cd /opt/mishakrug_tg_bot || { echo "Failed to cd into /opt/mishakrug_tg_bot"; exit 1; }
            sleep 5

            echo "Stopping existing process..."
            if pgrep -f "python3 mishakrug.py"; then
              echo "Stopping process..."
              sudo pkill -f "python3 mishakrug.py" > /dev/null 2>&1 || true
            sleep 5
            # Проверяем, завершился ли процесс
            if pgrep -f "python3 mishakrug.py"; then
              echo "Process is still running. Force killing..."
              sudo pkill -9 -f "python3 mishakrug.py" > /dev/null 2>&1 || true
            fi
            else
              echo "No running process found."
            fi
            sleep 5

            echo "Updating repository..."
            git pull origin main || { echo "Failed to update repository"; exit 1; }
            sleep 5

            echo "Starting new process..."
            source venv/bin/activate || { echo "Failed to activate virtual environment"; exit 1; }
            nohup python3 mishakrug.py > mishakrug.log 2>&1 &
            sleep 5

            echo "Deployment complete."
