name: Deploy Bot (Simple)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: mishadeploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 30s
          command_timeout: 30m
          script: |
            echo "Starting deployment..."
            
            # Stop old processes
            echo "Stopping old processes..."
            pids=$(pgrep -f "python3 mishakrug.py" || true)
            if [ -n "$pids" ]; then
              echo "Found processes: $pids"
              kill $pids || true
              sleep 3
              kill -9 $pids 2>/dev/null || true
            fi
            
            # Go to deployment directory
            echo "Preparing deployment directory..."
            cd /opt
            
            # Backup important files
            if [ -f "mishakrug_tg_bot/.env" ]; then
              echo "Backing up .env file..."
              cp mishakrug_tg_bot/.env /tmp/env_backup || true
            fi
            
            if [ -d "mishakrug_tg_bot/venv" ]; then
              echo "Backing up virtual environment..."
              cp -r mishakrug_tg_bot/venv /tmp/venv_backup || true
            fi
            
            # Remove old version
            echo "Removing old version..."
            rm -rf mishakrug_tg_bot || true
            
            # Clone repository
            echo "Cloning repository..."
            git clone https://github.com/devilcrowley/mishakrug_tg_bot.git
            if [ ! -d "mishakrug_tg_bot" ]; then
              echo "ERROR: Failed to clone repository"
              exit 1
            fi
            
            cd mishakrug_tg_bot
            
            # Restore files
            if [ -f "/tmp/env_backup" ]; then
              echo "Restoring .env file..."
              cp /tmp/env_backup .env
              rm /tmp/env_backup || true
            fi
            
            # Setup virtual environment
            if [ -d "/tmp/venv_backup" ]; then
              echo "Restoring virtual environment..."
              cp -r /tmp/venv_backup venv
              rm -rf /tmp/venv_backup || true
            else
              echo "Creating new virtual environment..."
              python3 -m venv venv
            fi
            
            # Install dependencies
            echo "Installing dependencies..."
            source venv/bin/activate
            if [ -f "requirements.txt" ]; then
              pip install -r requirements.txt
            fi
            
            # Start bot
            echo "Starting bot..."
            nohup python3 mishakrug.py > mishakrug.log 2>&1 &
            
            # Check if started
            sleep 3
            if pgrep -f "python3 mishakrug.py" > /dev/null; then
              echo "SUCCESS: Bot started successfully!"
              echo "PID: $(pgrep -f 'python3 mishakrug.py')"
            else
              echo "ERROR: Bot failed to start!"
              if [ -f "mishakrug.log" ]; then
                echo "Last 10 lines of log:"
                tail -10 mishakrug.log
              fi
              exit 1
            fi
            
            echo "Deployment completed successfully!"
