name: Deploy Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Позволяет запускать workflow вручную

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 30s
          command_timeout: 30m
          script_stop: true
          script: |
            cd /opt/mishakrug_tg_bot
            sleep 5
            git pull origin main
            sleep 5
            pkill -f "python3 mishakrug.py" || true
            sleep 5
            nohup python3 mishakrug.py > mishakrug.log 2>&1 &
            sleep 5
