name: Deploy Bot from custom branch

on:
  push:
    branches:
      - '**'  # Запускать для всех веток (или укажите конкретные, если нужно)
  workflow_dispatch:  # Позволяет запускать workflow вручную

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug secrets
        run: |
          if [ -z "${{ secrets.SERVER_HOST }}" ]; then
            echo "Error: SERVER_HOST is not set"
            exit 1
          fi
          echo "SERVER_HOST is configured"
      
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}  # Используем текущую ветку

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: mishadeploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 30s
          command_timeout: 30m
          script: |
            # debug_mode set -x
            echo "Setup deployment directory..."
            cd /opt/mishakrug_tg_bot || { echo "Failed to cd into /opt/mishakrug_tg_bot"; exit 1; }
            sleep 5
            
            # Улучшенная остановка процессов
            stop_process() {
              echo "Поиск процессов..."
              # Точное совпадение имени процесса
              pids=$(ps aux | grep "python3 mishakrug.py" | grep -v grep || true)
              
              if [ -n "$pids" ]; then
                echo "Найдены процессы: $pids"
                echo "Отправка SIGTERM..."
                kill $pids || true
                
                # Ожидание завершения с таймаутом
                timeout=10
                while [ $timeout -gt 0 ]; do
                  if ! ps aux | grep "python3 mishakrug.py" | grep -v grep >/dev/null; then
                    break
                  fi
                  sleep 1
                  ((timeout--))
                done
                
                if [ $timeout -eq 0 ]; then
                  echo "Принудительное завершение..."
                  kill -9 $pids || true
                  sleep 3
                fi
              fi
              
              # Финальная проверка
              if ps aux | grep "python3 mishakrug.py" | grep -v grep; then
                echo "ОШИБКА: Процессы остались!"
                exit 1
              fi
            }
          
            # Вызов функции остановки
            stop_process
          
            # Обновление и запуск (используем текущую ветку вместо main)
            git fetch origin
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            
            source venv/bin/activate
            nohup python3 mishakrug.py > mishakrug.log 2>&1 &
          
            # Проверка запуска
            sleep 3
            if ! ps aux | grep "python3 mishakrug.py" | grep -v grep >/dev/null; then
              echo "ОШИБКА: Процесс не запустился!"
              exit 1
            fi
          
            echo "Деплой успешно завершён! Ветка: ${{ github.ref_name }}"
