name: Deploy Bot (Clean)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: mishadeploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 30s
          command_timeout: 30m
          script: |
            set -e
            
            echo "=== Остановка старых процессов ==="
            pkill -f "python3 mishakrug.py" || echo "Процессы не найдены"
            sleep 2
            
            echo "=== Подготовка директории ==="
            cd /opt
            
            # Сохраняем .env если есть
            if [ -f "mishakrug_tg_bot/.env" ]; then
              echo "Сохраняем .env файл..."
              cp mishakrug_tg_bot/.env /tmp/mishakrug_env_backup
            fi
            
            # Сохраняем venv если есть
            if [ -d "mishakrug_tg_bot/venv" ]; then
              echo "Сохраняем виртуальное окружение..."
              cp -r mishakrug_tg_bot/venv /tmp/mishakrug_venv_backup
            fi
            
            echo "=== Удаление старой версии ==="
            rm -rf mishakrug_tg_bot
            
            echo "=== Клонирование репозитория ==="
            git clone https://github.com/devilcrowley/mishakrug_tg_bot.git
            cd mishakrug_tg_bot
            
            echo "=== Восстановление файлов ==="
            # Восстанавливаем .env
            if [ -f "/tmp/mishakrug_env_backup" ]; then
              echo "Восстанавливаем .env файл..."
              cp /tmp/mishakrug_env_backup .env
              rm /tmp/mishakrug_env_backup
            fi
            
            # Восстанавливаем или создаем venv
            if [ -d "/tmp/mishakrug_venv_backup" ]; then
              echo "Восстанавливаем виртуальное окружение..."
              cp -r /tmp/mishakrug_venv_backup venv
              rm -rf /tmp/mishakrug_venv_backup
            else
              echo "Создаем новое виртуальное окружение..."
              python3 -m venv venv
            fi
            
            echo "=== Установка зависимостей ==="
            source venv/bin/activate
            if [ -f "requirements.txt" ]; then
              pip install -r requirements.txt
            fi
            
            echo "=== Запуск бота ==="
            nohup python3 mishakrug.py > mishakrug.log 2>&1 &
            
            echo "=== Проверка запуска ==="
            sleep 3
            if pgrep -f "python3 mishakrug.py" > /dev/null; then
              echo "✅ Бот успешно запущен!"
              echo "PID: $(pgrep -f 'python3 mishakrug.py')"
            else
              echo "❌ ОШИБКА: Бот не запустился!"
              echo "Последние строки лога:"
              tail -10 mishakrug.log || echo "Лог файл не найден"
              exit 1
            fi
            
            echo "🎉 Деплой завершен успешно!"
