name: Deploy Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Позволяет запускать workflow вручную

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug secrets
        run: |
          if [ -z "${{ secrets.SERVER_HOST }}" ]; then
            echo "Error: SERVER_HOST is not set"
            exit 1
          fi
          echo "SERVER_HOST is configured"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: mishadeploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 30s
          command_timeout: 30m
          script: |
            echo "Переход в рабочую директорию..."
            cd /opt/mishakrug_tg_bot || { echo "Ошибка: Не удалось перейти в /opt/mishakrug_tg_bot"; exit 1; }

            # 1. Остановка текущего процесса (если запущен)
            stop_process() {
              echo "Поиск запущенных процессов..."
              pids=$(pgrep -f "python3 mishakrug.py" || true)
              
              if [ -n "$pids" ]; then
                echo "Найдены процессы: $pids"
                echo "Остановка..."
                kill $pids || true
                
                # Ожидание завершения (10 сек)
                timeout=10
                while kill -0 $pids 2>/dev/null && [ $timeout -gt 0 ]; do
                  sleep 1
                  ((timeout--))
                done
                
                # Принудительное завершение, если не остановился
                if kill -0 $pids 2>/dev/null; then
                  echo "Принудительное завершение (SIGKILL)..."
                  kill -9 $pids || true
                  sleep 2
                fi
              fi
            }
            stop_process

            # 2. Сохраняем .env (если существует)
            if [ -f .env ]; then
              echo "Сохранение .env во временный файл..."
              cp .env /tmp/mishakrug_env_backup
            fi

            # 3. Жесткий сброс репозитория (git reset --hard + pull)
            echo "Сброс репозитория и обновление..."
            git fetch origin
            git reset --hard origin/main
            git clean -fd  # Удаляет untracked файлы (кроме .env, т.к. он уже сохранён)

            # 4. Восстанавливаем .env (если был сохранён)
            if [ -f /tmp/mishakrug_env_backup ]; then
              echo "Восстановление .env..."
              mv /tmp/mishakrug_env_backup .env
            fi

            # 5. Запуск бота
            echo "Запуск бота..."
            source venv/bin/activate
            nohup python3 mishakrug.py > mishakrug.log 2>&1 &
            
            # Проверка, что процесс запустился
            sleep 3
            if ! pgrep -f "python3 mishakrug.py" >/dev/null; then
              echo "ОШИБКА: Процесс не запустился!"
              exit 1
            fi

            echo "✅ Деплой успешно завершён!"
